// File generated by FlutterFire CLI & Masrofaty Configuration
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_WEB_API_KEY', defaultValue: 'AIzaSyD-0JTojIURXvV54Ip14HPCv2jh_Xxz8a8'),
    appId: '1:309719860143:web:masrofatywebclientid',
    messagingSenderId: '309719860143',
    projectId: 'masrofaty-sync',
    authDomain: 'masrofaty-sync.firebaseapp.com',
    storageBucket: 'masrofaty-sync.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_ANDROID_API_KEY', defaultValue: 'AIzaSyD-0JTojIURXvV54Ip14HPCv2jh_Xxz8a8'),
    appId: '1:309719860143:android:be0f6a910e2dc81b78e55a',
    messagingSenderId: '309719860143',
    projectId: 'masrofaty-sync',
    storageBucket: 'masrofaty-sync.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_IOS_API_KEY', defaultValue: 'AIzaSyDejltZCbzRDSJlulUS8OX0oQ1CyUl5ey8'),
    appId: '1:309719860143:ios:df4662df8457584678e55a',
    messagingSenderId: '309719860143',
    projectId: 'masrofaty-sync',
    storageBucket: 'masrofaty-sync.firebasestorage.app',
    iosBundleId: 'com.masrofaty.app.masrofaty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_MACOS_API_KEY', defaultValue: 'AIzaSyDejltZCbzRDSJlulUS8OX0oQ1CyUl5ey8'),
    appId: '1:309719860143:ios:df4662df8457584678e55a',
    messagingSenderId: '309719860143',
    projectId: 'masrofaty-sync',
    storageBucket: 'masrofaty-sync.firebasestorage.app',
    iosBundleId: 'com.masrofaty.app.masrofaty',
  );
}
