// File generated by FlutterFire CLI & Masrofaty Configuration
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_WEB_API_KEY', defaultValue: 'YOUR_WEB_API_KEY'),
    appId: '1:102938475610:web:abcdef1234567890',
    messagingSenderId: '102938475610',
    projectId: 'masrofaty-app',
    authDomain: 'masrofaty-app.firebaseapp.com',
    storageBucket: 'masrofaty-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_ANDROID_API_KEY', defaultValue: 'YOUR_ANDROID_API_KEY'),
    appId: '1:102938475610:android:fedcba0987654321',
    messagingSenderId: '102938475610',
    projectId: 'masrofaty-app',
    storageBucket: 'masrofaty-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_IOS_API_KEY', defaultValue: 'YOUR_IOS_API_KEY'),
    appId: '1:102938475610:ios:1122334455667788',
    messagingSenderId: '102938475610',
    projectId: 'masrofaty-app',
    storageBucket: 'masrofaty-app.appspot.com',
    iosBundleId: 'com.masrofaty.app.masrofaty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_MACOS_API_KEY', defaultValue: 'YOUR_MACOS_API_KEY'),
    appId: '1:102938475610:ios:9988776655443322',
    messagingSenderId: '102938475610',
    projectId: 'masrofaty-app',
    storageBucket: 'masrofaty-app.appspot.com',
    iosBundleId: 'com.masrofaty.app.masrofaty',
  );
}
